matrix:
  include:
  - os: osx
    osx_image: xcode9.3beta
    env:
    - MATRIX_EVAL=""

before_install:
  - eval "${MATRIX_EVAL}"
  - brew update
  - brew bundle
  - env
  - pip install pathlib2

install:
  - gem install dropbox-deployment
  - git clone https://github.com/kristovatlas/osx-config-check
  - cd osx-config-check ; python2.7 app.py --report-only --skip-sudo-checks ; cd ..

script:
  - ./build4mac.py -p B37 -q Qt5Brew -c
  - source filter-clang.sh; ./build4mac.py -p B37 -q Qt5Brew | filter
  - ./build4mac.py -p B37 -q Qt5Brew -y
  - qt5.pkg.macos-HighSierra-release/klayout.app/Contents/MacOS/klayout -b -r test-pylib-script.py
  - cd qt5.build.macos-HighSierra-release
  - ln -s klayout.app/Contents/MacOS/klayout klayout
  - export TESTTMP=testtmp    # path to a directory that will hold temporary data (will be created)
  - export TESTSRC=..         # path to the source directory
  - ./ut_runner -h
  - ./ut_runner -s || true
  - cd ..
  - export gitcommit=$(git rev-parse --short HEAD)
  - mkdir deploy
  - tar czf "deploy/qt5.pkg.macos-HighSierra-release-$gitcommit.tar.gz" qt5.pkg.macos-HighSierra-release

after_success:
  - dropbox-deployment
