matrix:
  include:
  # Python 3
    - os: osx
      osx_image: xcode9.4  # macOS 10.13
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=B37
        - MACOS_VERSION=HighSierra
    - os: osx
      osx_image: xcode8.3  # macOS 10.12
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=B37
        - MACOS_VERSION=Sierra
    - os: osx
      osx_image: xcode8  # macOS 10.11
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=B37
        - MACOS_VERSION=ElCapitan

    # Python 2
    - os: osx
      osx_image: xcode9.4  # macOS 10.13
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=HighSierra
    - os: osx
      osx_image: xcode8.3  # macOS 10.12
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=Sierra
    - os: osx
      osx_image: xcode8  # macOS 10.11
      env:
        - MATRIX_EVAL=""
        - PYTHON_VERSION=Sys
        - MACOS_VERSION=ElCapitan

before_install:
  - eval "${MATRIX_EVAL}"
  - brew update
  - brew bundle
  - env

install:
  - gem install dropbox-deployment
  - git clone https://github.com/kristovatlas/osx-config-check
  - cd osx-config-check ; python2.7 app.py --report-only --skip-sudo-checks ; cd ..

script:
  - make build
  - make deploy
  - make test
  - make dropbox-deploy

after_success:
  - dropbox-deployment
